spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://localhost:3306/phone_store?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true&serverTimezone=UTC"
    username: ${DATABASE_USERNAME:root}
    password: ${DATABASE_PASSWORD:root}
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 5MB
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        show_sql: false
    defer-datasource-initialization: true


